models:
  - name: clientes
    enabled: true
    materialized: table
    description: "Tabela de clientes"
    columns:
      - name: id_cliente
        description: "ID do cliente"
        tests:
          - unique
          - not_null
      - name: nome_completo
        description: "Nome completo do cliente"
        tests:
          - not_null
      - name: primeiro_pedido
        description: "Primeiro pedido do cliente"
      - name: pedido_mais_recente
        description: "Pedido mais recente do cliente"
      - name: pagamento_total
        description: "Valor total do pagamento do cliente"


  - name: pedidos
    enabled: true
    materialized: table
    description: "Tabela de pedidos"
    columns:
      - name: id_pedido
        description: "ID do pedido"
        tests:
          - unique
          - not_null
      - name: id_cliente
        description: "ID do cliente que fez o pedido"
        tests:
          - not_null
      - name: data_pedido
        description: "Data do pedido"
        tests:
          - not_null
      - name: status
        description: "Status do pedido (ex: 'pending', 'completed', 'cancelled')"
        tests:
          - not_null
      - name: credit_card_amount
        description: Amount of the order (BRL) paid for by credit card
      - name: coupon_amount
        description: Amount of the order (BRL) paid for by coupon
      - name: bank_transfer_amount
        description: Amount of the order (BRL) paid for by bank transfer
      - name: gift_card_amount
        description: Amount of the order (BRL) paid for by gift card
