version: 2

models:
  - name: exemplo_incremental_clientes
    enabled: true
    materialized: table
    columns:
      - name: id_cliente
        tests:
          - unique
          - not_null

  - name: exemplo_incremental_pedidos
    columns:
      - name: id_pedido
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  - name: exemplo_incremental_pagamentos
    columns:
      - name: id_pagamento
        tests:
          - unique
          - not_null
      - name: metodo_pagamento
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
